site_name: BES Playbook
theme:
  name: null
  custom_dir: 'bes-theme'
  navigation_depth: 2
markdown_extensions:
  - attr_list
  - extra
plugins:
  - search
nav:
  - Home: index.md
  - Agile:
      - 1. Overview:
          - 1.1 Purpose: agile/1-1-purpose.md
          - 1.2 Audience: agile/1-2-audience.md
          - 1.3 References: agile/1-3-references.md
      - 2. Agile Transformation:
          - 2.1 Waterfall Background: agile/2-1-waterfall.md
          - 2.2 Introduction: agile/2-2-introduction.md
      - 3. Applying Agile Methods and Mindset Within The Air Force:
          - 3.0 Overview: agile/3-0-overview.md
          - 3.1 Agile Contracting: agile/3-1-contracting.md
          - 3.2 Agile Stakeholder: agile/3-2-stakeholder.md
          - 3.3 Project Management: agile/3-3-projectmanagement.md
          - 3.4 Agile CDRLs and Delivery: agile/3-4-delivery.md
          - 3.5 Status Reporting: agile/3-5-metrics.md
      - 4. Agile Architecture:
          - 4.1 Agile Management Tools: agile/4-1-architecture.md
      - 5. Agile Framework:
          - 5.1 Part I - Establish the Product Backlog (PB) and Constraints: agile/5-1-backlog.md
          - 5.2 Part II - Establish the Methodology: agile/5-2-methodology.md
          - 5.3 Kanban: agile/5-3-kanban.md
          - 5.4 Extreme Programming: agile/5-4-xp.md
          - 5.5 Part III - Establish the Team: agile/5-5-team.md
      - 6. Appendix A - Key Event Plays:
          - 6.1 Scrum: agile/6-1-scrum.md
          - 6.2 Kanban: agile/6-2-kanban.md
          - 6.3 Extreme Programming: agile/6-3-xp.md
      - 7. Appendix B - Key Personal Plays:
          - 7.1 Agile Lead: agile/7-1-lead.md
          - 7.2 Product Owner: agile/7-2-owner.md
          - 7.3 Business Analyst: agile/7-3-analyst.md

      - 8. Appendix C - Key Links:
          - 8.1 Agile in General: agile/8-1-general.md
          - 8.2 Agile Tools: agile/8-2-tools.md
      - 9. Appendix D - Agile Terminology: 
          - 9.1 Agile Terminology: agile/9-1-appendix-d.md
      - 10. Appendix E - Glossary:
          - 10.1 Glossary: agile/10-1-appendix-e.md

  - Agile Model-Driven Functionality Improvement:
      - 1. Plays:
          - 1.1 Overview: agile-model/1-1-plays.md
      - 2. Overview:
          - 2.1 Introduction: agile-model/2-1-intro.md
          - 2.2 Problem Statement: agile-model/2-2-problem.md
          - 2.3 Purpose: agile-model/2-3-purpose.md
          - 2.4 Scope: agile-model/2-4-scope.md
          - 2.5 Intended Audience: agile-model/2-5-audience.md
          - 2.6 Benefits: agile-model/2-6-benefits.md
      - 3. Agile Model-Driven Functionality Improvement:
          - 3.1 Standards: agile-model/3-1-standards.md
          - 3.2 Methodologies: agile-model/3-2-methodologies.md
          - 3.3 Common Use Case: agile-model/3-3-usecases.md
          - 3.4 Lessons: agile-model/3-4-lessons.md
          - 3.5 Limitations: agile-model/3-5-limitations.md
          - 3.6 Recommendations: agile-model/3-6-recommendations.md
      - 4. Organization and Support:
          - 4.1 Key Stakeholders: agile-model/4-1-stakeholders.md
          - 4.2 subpages:
              - 4.2.1 Project Management Team: agile-model/4-2-1-management.md
              - 4.2.2 Technical Team: agile-model/4-2-2-tech.md
              - 4.2.3 Business Analyst SME's: agile-model/4-2-3-business.md
          - 4.2 Team Structure: agile-model/4-2-team.md
          - 4.3 Support: agile-model/4-3-support.md
      - 5. Lifecycle Process:
          - 5.1 Best Practices: agile-model/5-1-bestpractices.md
      - 6. Project Guidance:
          - 6.1 Phases: agile-model/6-1-phases.md
          - 6.2 Risk Identification and Management: agile-model/6-2-risk.md
      - 7. Management and Metrics:
          - 7.1 Define KPI's: agile-model/7-1-definekpi.md
      - 8. Solution Design:
          - 8.1 Requirements Analysis: agile-model/8-1-requirements.md
          - 8.2 Technical Design: agile-model/8-2-techdesign.md
          - 8.3 Cybersecurity Considerations: agile-model/8-3-cybersecurity.md
      - 9. Determining the Best "Low-Code" Solution Process:
          - 9.1 Identifying Viable Solutions: agile-model/9-1-solutions.md
          - 9.2 Conducting Analysis: agile-model/9-2-analysis.md
            # - : agile-model/9-b-1-besttools.md
          - 9.3 subpages:
              - 9.3.1 Pega Platform: agile-model/9-3-1-pega.md
              - 9.3.2 Appian Low-Code Platform: agile-model/9-3-2-appian.md
              - 9.3.3 Mendix Low-Code Platform: agile-model/9-3-3-mendix.md
              - 9.3.4 Microsoft PowerApps: agile-model/9-3-4-microsoft.md
              - 9.3.5 OutSystems Low-Code Platform: agile-model/9-3-5-outsystems.md
              - 9.3.6 Kony Quantum: agile-model/9-3-6-kony.md
          - 9.3 Help COTS Too Is Available - Example List: agile-model/9-3-cots.md
      - 10. Appendix:
          - '10.1 Appendix A: Sample Design 1': agile-model/10-appendix-a.md
          - '10.2 Appendix B: Sample Design 2': agile-model/10-appendix-b.md
          - '10.3 Appendix C: Checklists and Templates': agile-model/10-appendix-c.md
  - Automated Testing:
      - 1. Overview: testing/1-1-testing.md
  - User Experience:
      - 1. Overview:
          - 1.1 Purpose: ux/1-1-purpose.md
          - 1.2 Audience: ux/1-2-audience.md
          - 1.3 Benefits of UX: ux/1-3-benefits.md
          - 1.4 Levels of Design Maturity: ux/1-4-maturity.md
      - 2. User Experience:
          - 2.1 What is UX?: ux/2-1-what-is-ux.md
          - 2.2 UX Disciplines & Project Roles: ux/2-2-disciplines.md
          - 2.3 UX in Software Lifecycle Methodologies: ux/2-3-lifecycle.md
      - 3. UX Principles & Methodology:
          - 3.1 UX Principles: ux/3-1-principles.md
          - 3.2 UX Methodology: ux/3-2-methodology.md
          - 3.3 subpages:
              - Interviews: ux/3-3-1-1-interviews.md
              - Surveys: ux/3-3-1-2-surveys.md
              - Site metrics analysis: ux/3-3-1-3-metrics.md
              - Diary studies: ux/3-3-1-4-diary.md
              - Personas: ux/3-3-2-1-personas.md
              - User Scenarios: ux/3-3-2-2-scenarios.md
              - Journey maps: ux/3-3-2-3-journey.md
              - Service design blueprints: ux/3-3-2-4-blueprints.md
              - Use cases: ux/3-3-2-5-usecase.md
          - '3.3 Phase 1: Research & Discovery': ux/3-3-research.md
          - 3.4 subpages:
              - Wireframing/sketching: ux/3-4-1-1-wireframe.md
              - Information architecture: ux/3-4-1-2-ia.md
              - Participatory design: ux/3-4-1-3-participatory.md
              - Concept testing: ux/3-4-1-4-concept.md
              - Roadmapping: ux/3-4-2-1-roadmapping.md
              - Story writing: ux/3-4-2-2-story.md
          - '3.4 Phase 2: Conceptual Design': ux/3-4-conceptual.md
          - 3.5 subpages:
              - High-fidelity wireframing and visual design: ux/3-5-1-1-visualdesign.md
              - Prototyping: ux/3-5-1-2-prototyping.md
              - Usability testing: ux/3-5-1-3-usability.md
              - Specifying/annotating: ux/3-5-1-4-annotating.md
          - '3.5 Phase 3: Detailed Design': ux/3-5-detailed.md
          - '3.6 Phase 4: Support': ux/3-6-support.md
      - 4. Web Design Standards:
          - 4.1 Introduction: ux/4-1-introduction.md
          - 4.2 General Interface Guidelines: ux/4-2-guidelines.md
          - 4.3 Grids & Breakpoints: ux/4-3-grids.md
          - 4.4 Branding/Logo: ux/4-4-branding.md
          - 4.5 Global Headers & Footers: ux/4-5-headers.md
          - 4.6 Page Layouts: ux/4-6-layouts.md
          - 4.7 Typography: ux/4-7-typography.md
          - 4.8 Color: ux/4-8-color.md
          - 4.9 Iconography: ux/4-9-icons.md
          - 4.10 Imagery: ux/4-10-imagery.md
          - 4.11 Buttons & Controls: ux/4-11-buttons.md
          - 4.12 Key Mobile Standards: ux/4-12-mobile.md
          - 4.13 Accessibility: ux/4-13-accessibility.md
      - 5. Component Library:
          - 5.1 Introduction: ux/5-1-intro.md
          - 5.2 Global Navigation: ux/5-2-nav.md
          - 5.3 Icons: ux/5-3-icons.md
          - 5.4 Buttons & Labels: ux/5-4-buttons.md
          - 5.5 Content Modules: ux/5-5-modules.md
          - 5.6 Alerts & Messaging: ux/5-6-alerts.md
          - 5.7 Forms & Controls: ux/5-7-forms.md
          - 5.8 Visualizations: ux/5-8-visualizations.md
          - 5.9 Key Mobile Components: ux/5-9-mobile.md
      - 6. Appendix:
          - 6.1 Additional Resources: ux/6-1-appendix.md
          - 6.2 Alpha Standard Layouts: ux/6-2-layouts.md
  - DevSec Ops:
      - 1. Overview: devops/1-1-devops.md
  - Cyber Security:
      - 1. Overview: cyber/1-1-cyber.md
  - App Technology Refresh for Cloud:
      - 1. Overview: cloud/1-1-cloud.md
  - Agile Acquistions:
      - 1. Overview: acquistions/1-1-acquistions.md
  - Automated Application Management:
      - 1. Plays:
          - 1.1 Applications Future Lifespan: modern/1-1-play-1.md
          - 1.2 Technical Baseline: modern/1-2-play-2.md
          - 1.3 Modernization Options: modern/1-3-play-3.md
          - 1.4 Target Application Solution: modern/1-4-play-4.md
          - 1.5 Modernization and Migration Plan: modern/1-5-play-5.md
          - 1.6 Executing the Plan: modern/1-6-play-6.md
      - 2. Overview:
          - 2.1 Introduction: modern/2-1-intro.md
          - 2.2 Problem Statement: modern/2-2-problem.md
          - 2.3 Purpose: modern/2-3-purpose.md
          - 2.4 Scope: modern/2-4-scope.md
          - 2.5 Audience: modern/2-5-audience.md
          - 2.6 Benefits: modern/2-6-benefits.md
      - 3. Automated Application Modernization:
          - 3.1 Guidance: modern/3-1-guidance.md
          - 3.2 Standards: modern/3-2-standards.md
          - 3.3 Common Use Case: modern/3-3-common.md
          - 3.4 Approaches: modern/3-4-approaches.md
          - 3.5 Methodologies: modern/3-5-methodologies.md
          - 3.6 Patterns: modern/3-6-patterns.md
          - 3.7 Barriers and Challenges: modern/3-7-barriers.md
          - 3.8 Recommendations: modern/3-8-recommendations.md
          - 3.9 Lessons: modern/3-9-lessons.md
          - 3.10 Limitations: modern/3-10-limitations.md
      - 4. Modernization Tools:
          - 4.1 Tool Types: modern/4-1-tooltypes.md
          - 4.2 Tool Matrix: modern/4-2-toolmatrix.md
      - 5. Lifecycle Processes:
          - 5.1 Best Practices: modern/5-1-best.md
      - 6. Organization and Support:
          - 6.1 Project Team: modern/6-1-project.md
          - 6.2 Technical Team: modern/6-2-tech.md
          - 6.3 Support: modern/6-3-support.md
          - 6.4 Stakeholders: modern/6-4-stakeholders.md
      - 7. Determining the Best Modernization Solution:
          - 7.1 Identifying Viable Solutions: modern/7-1-solutions.md
          - 7.2 Analysis of Alternatives (AoA) Guidance: modern/7-2-alternatives.md
      - 8. Solution Design:
          - 8.1 Requirements: modern/8-1-requirements.md
          - 8.2 Technical Design: modern/8-2-tech.md
          - 8.3 Cybersecurity: modern/8-3-cybersecurity.md
      - 9. Project Guidance:
          - 9.1 Phases: modern/9-1-phases.md
          - 9.2 Risk Identification and Management: modern/9-2-risk.md
      - 10. Measurement and Metrics:
          - 10.1 Define KPIs: modern/10-1-definekpi.md
      - 11. Appendix:
          - '11.1 Appendix A: Sample Design 1': modern/11-appendix-a.md
          - '11.2 Appendix B: Sample Design 2': modern/11-appendix-b.md
          - '11.3 Appendix C: Checklists and Templates': modern/11-appendix-c.md

extra:
  # Update the baseurl for the location of deployment.
  # This value is combined with the playbook urls to build the inter-playbook nav
  # baseurl: https://isobar-us.github.io/USAF-2212-A4UX-Playbook
  baseurl: https://ArrayBESPlaybooks.github.io/ArrayBESPlaybook
  # baseurl: http://localhost:8000

  # This list
  playbooks:
    - name: Agile
      url: /agile/1-1-purpose
      icon: _assets/0_home_page_icon_agile.svg
      desc: Faster, more dynamic response to customersâ€™ development needs requires a modern management approach. Learn what is necessary to establish those responsive process and management guidelines within the DoD environment.
    - name: Automated Testing
      url: /testing/1-1-testing
      icon: _assets/0_home_page_icon_automatedtesting.svg
      desc: With the move towards more flexible approaches to software development comes the desire to implement faster, more reliable testing procedures. Learn practical, experienced-based methods and best practices for automating testing.
    - name: User Experience
      url: /ux/1-1-purpose
      icon: _assets/0_home_page_icon_user_experience.svg
      desc: Delivering value requires delivering an experience that meets the needs of your users. Learn what UX is, how it benefits and enhances development efforts, methods for designing experiences, and best-practice visual design guidelines.
    - name: Agile Model-Driven Functionality Improvement
      url: /agile-model/1-1-plays
      icon: _assets/0_home_page_icon_agile_Model-Driven.svg
    - name: Automated Application Modernization
      url: /modern/1-1-play-1
      icon: _assets/0_home_page_icon_automated_App_modern.svg
    # - name: DevSec Ops
    #   url: /devops/1-1-devops
    #   icon: _assets/0_home_page_icon_devsec.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus.
    # - name: Cyber Security
    #   url: /cyber/1-1-cyber
    #   icon: _assets/0_home_page_icon_security.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium.
    # - name: App Technology Refresh for Cloud
    #   url: /cloud/1-1-cloud
    #   icon: _assets/0_home_page_icon_cloud.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus, id ornare lectus. purus non justo.
    # - name: Agile Acquistions
    #   url: /acquistions/1-1-acquistions
    #   icon: _assets/0_home_page_icon_agile_acquistions.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus, id ornare lectus.

  footer:
    AFLCMC/BES:
      Air Force Life Cycle Management Center (AFLCMC): https://www.wpafb.af.mil/aflcmc
      Air Force Business and Enterprise Systems (BES): https://www.airforcebes.af.mil

  section_headers:
    - ../../_assets/_headers/Header01.jpg
    - ../../_assets/_headers/Header02.jpg
    - ../../_assets/_headers/Header03.jpg
    - ../../_assets/_headers/Header04.jpg
    - ../../_assets/_headers/Header05.jpg
    - ../../_assets/_headers/Header06.jpg
    - ../../_assets/_headers/Header07.jpg
    - ../../_assets/_headers/Header08.jpg
    - ../../_assets/_headers/Header09.jpg
  home_headers:
    - _assets/0_home_page_header_01@2x.jpg
    - _assets/0_home_page_header_02@2x.jpg
    - _assets/0_home_page_header_03@2x.jpg
    - _assets/0_home_page_header_04@2x.jpg
