site_name: BES Playbook
theme:
  name: null
  custom_dir: 'bes-theme'
  navigation_depth: 2
markdown_extensions:
  - attr_list
  - extra
plugins:
  - search
nav:
  - Home: index.md
  - Agile:
      - 1. Overview:
          - 1.1 Purpose: agile/1-1-purpose.md
          - 1.2 Audience: agile/1-2-audience.md
          - 1.3 References: agile/1-3-references.md
      - 2. Agile Transformation:
          - 2.1 Waterfall Background: agile/2-1-waterfall.md
          - 2.2 Introduction: agile/2-2-introduction.md
      - 3. Applying Agile Methods and Mindset Within The Air Force:
          - 3.0 Overview: agile/3-0-overview.md
          - 3.1 Agile Contracting: agile/3-1-contracting.md
          - 3.2 Agile Stakeholder: agile/3-2-stakeholder.md
          - 3.3 Project Management: agile/3-3-projectmanagement.md
          - 3.4 Agile CDRLs and Delivery: agile/3-4-delivery.md
          - 3.5 Status Reporting: agile/3-5-metrics.md
      - 4. Agile Architecture:
          - 4.1 Agile Management Tools: agile/4-1-architecture.md
      - 5. Agile Framework:
          - 5.1 Part I - Establish the Product Backlog (PB) and Constraints: agile/5-1-backlog.md
          - 5.2 Part II - Establish the Methodology: agile/5-2-methodology.md
          - 5.3 Kanban: agile/5-3-kanban.md
          - 5.4 Extreme Programming: agile/5-4-xp.md
          - 5.5 Part III - Establish the Team: agile/5-5-team.md
      - 6. Appendix A - Key Event Plays:
          - 6.1 Scrum: agile/6-1-scrum.md
          - 6.2 Kanban: agile/6-2-kanban.md
          - 6.3 Extreme Programming: agile/6-3-xp.md
      - 7. Appendix B - Key Personal Plays:
          - 7.1 Agile Lead: agile/7-1-lead.md
          - 7.2 Product Owner: agile/7-2-owner.md
          - 7.3 Business Analyst: agile/7-3-analyst.md

      - 8. Appendix C - Key Links:
          - 8.1 Agile in General: agile/8-1-general.md
          - 8.2 Agile Tools: agile/8-2-tools.md
      - 9. Appendix D - Agile Terminology: 
          - 9.1 Agile Terminology: agile/9-1-appendix-d.md
      - 10. Appendix E - Glossary:
          - 10.1 Glossary: agile/10-1-appendix-e.md

  - Low-Code:
      - 1. Plays:
          - 1.1 Overview: low-code/1-1-plays.md
      - 2. Overview:
          - 2.1 Introduction: low-code/2-1-intro.md
          - 2.2 Problem Statement: low-code/2-2-problem.md
          - 2.3 Purpose: low-code/2-3-purpose.md
          - 2.4 Scope: low-code/2-4-scope.md
          - 2.5 Audience: low-code/2-5-audience.md
          - 2.6 Benefits: low-code/2-6-benefits.md
      - 3. Low-Code Application Development:
          - 3.1 What is Low-Code?: low-code/3-1-what-is.md
          - 3.2 Low-Code vs. No-Code Frameworks: low-code/3-2-vs-no-code.md
          - 3.3 Low-Code Use Cases: low-code/3-3-use-cases.md
          - 3.4 Low-Code Benefits: low-code/3-4-benefits.md
          - 3.5 Low-Code Limitations: low-code/3-5-limitations.md
      - 4. Low-Code Project Guidance:
          - 4.1 Team Structure: low-code/4-1-structure.md
          - 4.2 Project Management Processes: low-code/4-2-management-process.md
          - 4.3 Low-Code Software Development Lifecycle: low-code/4-3-dev-lifecycle.md
          - "4.4 Key Project Metrics – KPI’s": low-code/4-4-kpi.md
      - 5. Low-Code Platform Tool Selection Guidance:
          - 5.1 How to conduct Low-Code Platform Tool Analysis: low-code/5-1-analysis.md
          - 5.2 Current Market Leaders (Forrester, Gartner): low-code/5-1-market-leaders.md
      - 6. Appendix A – Air Force Low-Code Sample Applications:
          - 6.1 Air Force Contracting Information Technology (CON-IT): low-code/6-1-con-it.md
      - 7. Appendix B – Low-Code Platform Evaluation Criteria Template:
          - 7.1 Evaluation Template: low-code/7-1-evaluation.md
      - 8. Appendix C – Low-Code Terminology:
          - 8.1 Low-Code Terminology: low-code/8-1-terminology.md
      - 9. Appendix D – Glossary:
          - 9.1 Glossary: low-code/9-1-glossary.md
      - 10. Appendix E – References:
          - 10.1 References: low-code/10-1-references.md
      - 11. Appendix F – Chapter 5 Key Contributors:
          - 11.1 Chapter 5 Low-Code Playbook Contributors: low-code/11-1-contributors.md

  - Automated Testing:
      - 1. Overview:
        - 1.1 Purpose: testing/1-1-purpose.md
        - 1.2 Audience: testing/1-2-audience.md
        - 1.3 Benfits of Automated Testing: testing/1-3-benefits.md
      - 2. Test Automation:
        - 2.1 What is Automation?: testing/2-1-what.md
        - 2.2 Automation in Software Lifecycle Methodologies: testing/2-2-lifecycle.md
        - 2.3 Benefits to AF: testing/2-3-benefits.md
        - 2.4 Avoiding Pitfalls: testing/2-4-pitfalls.md
      - 3. Roles in Test Automation:
        - 3.1 Acquisitions: testing/3-1-acquisitions.md
        - 3.2 Management Support: testing/3-2-management.md
        - 3.3 Technical Support: testing/3-3-technical.md
        - 3.4 Domain Support: testing/3-4-domain.md
        - 3.5 Automation Team Members: testing/3-5-team.md
      - 4. Scope of Test Automation:
        - 4.1 Tools Target Areas: testing/4-1-tools.md
        - 4.2 Test Levels: testing/4-2-levels.md
        - 4.3 Test Types: testing/4-3-types.md
      - 5. Developing A Test Automation Solution:
        - 5.1 Approaches to Test Automation: testing/5-1-approach.md
        - 5.2 Overall Architectural Considerations: testing/5-2-architecture.md
        - 5.3 Evaluation and Selection of Test Tools: testing/5-3-evaluation.md
      - 6. Migrating From Manual to Automated Testing:
        - 6.1 What Makes Sense to Automate: testing/6-1-what.md
        - 6.2 When Should Automation Occur: testing/6-2-when.md
        - 6.3 Criteria for Creating New Automated Tests: testing/6-3-newtests.md
        - 6.4 Criteria for Converting Manual Tests to Automation: testing/6-4-manualtests.md
        - 6.5 Transitioning Staff to Automation: testing/6-5-transition.md
      - 7. Test Automation Development Lifecycle:
        - 7.1 Phases in Automation Development: testing/7-1-phases.md
        - 7.2 Similarities to Application Development: testing/7-2-appdev.md
        - 7.3 Similarities to Manual Testing: testing/7-3-manualtests.md
      - 8. Effectiveness Measurements:
        - 8.1 Effectiveness Measurements: testing/8-1-measurements.md
      - 9. Reporting:
        - 9.1 Reporting: testing/9-1-reporting.md
      - 10. Looking Ahead:
        - 10.1 Building Momentum in Test Automation: testing/10-1-momentum.md
        - 10.2 Keeping Abreast of the Technology Landscape: testing/10-2-landscape.md
        - 10.3 Continuous Improvement Activities: testing/10-3-improvements.md
        - 10.4 Making the Process Repeatable: testing/10-4-process.md
      - 11. Appendix:
        - '11.1 Appendix A: Resources': testing/11-1-resources.md
        - '11.2 Appendix B: Test Tools': testing/11-2-tools.md
  - User Experience:
      - 1. Overview:
          - 1.1 Purpose: ux/1-1-purpose.md
          - 1.2 Audience: ux/1-2-audience.md
          - 1.3 Benefits of UX: ux/1-3-benefits.md
          - 1.4 Levels of Design Maturity: ux/1-4-maturity.md
      - 2. User Experience:
          - 2.1 What is UX?: ux/2-1-what-is-ux.md
          - 2.2 UX Disciplines & Project Roles: ux/2-2-disciplines.md
          - 2.3 UX in Software Lifecycle Methodologies: ux/2-3-lifecycle.md
      - 3. UX Principles & Methodology:
          - 3.1 UX Principles: ux/3-1-principles.md
          - 3.2 UX Methodology: ux/3-2-methodology.md
          - 3.3 subpages:
              - Interviews: ux/3-3-1-1-interviews.md
              - Surveys: ux/3-3-1-2-surveys.md
              - Site metrics analysis: ux/3-3-1-3-metrics.md
              - Diary studies: ux/3-3-1-4-diary.md
              - Personas: ux/3-3-2-1-personas.md
              - User Scenarios: ux/3-3-2-2-scenarios.md
              - Journey maps: ux/3-3-2-3-journey.md
              - Service design blueprints: ux/3-3-2-4-blueprints.md
              - Use cases: ux/3-3-2-5-usecase.md
          - '3.3 Phase 1: Research & Discovery': ux/3-3-research.md
          - 3.4 subpages:
              - Wireframing/sketching: ux/3-4-1-1-wireframe.md
              - Information architecture: ux/3-4-1-2-ia.md
              - Participatory design: ux/3-4-1-3-participatory.md
              - Concept testing: ux/3-4-1-4-concept.md
              - Roadmapping: ux/3-4-2-1-roadmapping.md
              - Story writing: ux/3-4-2-2-story.md
          - '3.4 Phase 2: Conceptual Design': ux/3-4-conceptual.md
          - 3.5 subpages:
              - High-fidelity wireframing and visual design: ux/3-5-1-1-visualdesign.md
              - Prototyping: ux/3-5-1-2-prototyping.md
              - Usability testing: ux/3-5-1-3-usability.md
              - Specifying/annotating: ux/3-5-1-4-annotating.md
          - '3.5 Phase 3: Detailed Design': ux/3-5-detailed.md
          - '3.6 Phase 4: Support': ux/3-6-support.md
      - 4. Web Design Standards:
          - 4.1 Introduction: ux/4-1-introduction.md
          - 4.2 General Interface Guidelines: ux/4-2-guidelines.md
          - 4.3 Grids & Breakpoints: ux/4-3-grids.md
          - 4.4 Branding/Logo: ux/4-4-branding.md
          - 4.5 Global Headers & Footers: ux/4-5-headers.md
          - 4.6 Page Layouts: ux/4-6-layouts.md
          - 4.7 Typography: ux/4-7-typography.md
          - 4.8 Color: ux/4-8-color.md
          - 4.9 Iconography: ux/4-9-icons.md
          - 4.10 Imagery: ux/4-10-imagery.md
          - 4.11 Buttons & Controls: ux/4-11-buttons.md
          - 4.12 Key Mobile Standards: ux/4-12-mobile.md
          - 4.13 Accessibility: ux/4-13-accessibility.md
      - 5. Component Library:
          - 5.1 Introduction: ux/5-1-intro.md
          - 5.2 Global Navigation: ux/5-2-nav.md
          - 5.3 Icons: ux/5-3-icons.md
          - 5.4 Buttons & Labels: ux/5-4-buttons.md
          - 5.5 Content Modules: ux/5-5-modules.md
          - 5.6 Alerts & Messaging: ux/5-6-alerts.md
          - 5.7 Forms & Controls: ux/5-7-forms.md
          - 5.8 Visualizations: ux/5-8-visualizations.md
          - 5.9 Key Mobile Components: ux/5-9-mobile.md
      - 6. Appendix:
          - 6.1 Additional Resources: ux/6-1-appendix.md
          - 6.2 Alpha Standard Layouts: ux/6-2-layouts.md
  - DevSec Ops:
      - 1. Overview: devops/1-1-devops.md
  - Cyber Security:
      - 1. Overview: cyber/1-1-cyber.md
  - App Technology Refresh for Cloud:
      - 1. Overview: cloud/1-1-cloud.md
  - Agile Acquistions:
      - 1. Overview: acquistions/1-1-acquistions.md
  - Automated Application Modernization:
      - 1. Plays:
          - "1.1 Application's Future Lifespan": modern/1-1-play-1.md
          - 1.2 Technical Baseline: modern/1-2-play-2.md
          - 1.3 Modernization Options: modern/1-3-play-3.md
          - 1.4 Target Application Solution: modern/1-4-play-4.md
          - 1.5 Modernization and Migration Plan: modern/1-5-play-5.md
          - 1.6 Executing the Plan: modern/1-6-play-6.md
      - 2. Overview:
          - 2.1 Introduction: modern/2-1-intro.md
          - 2.2 Problem Statement: modern/2-2-problem.md
          - 2.3 Purpose: modern/2-3-purpose.md
          - 2.4 Scope: modern/2-4-scope.md
          - 2.5 Audience: modern/2-5-audience.md
          - 2.6 Benefits: modern/2-6-benefits.md
      - 3. Automated Application Modernization:
          - 3.0 Overview: modern/3-0-overview.md
          - 3.1 Guidance: modern/3-1-guidance.md
          - 3.2 Standards: modern/3-2-standards.md
          - 3.3 Common Use Case: modern/3-3-common.md
          - 3.4 Approaches: modern/3-4-approaches.md
          - 3.5 Methodologies: modern/3-5-methodologies.md
          - 3.6 Patterns: modern/3-6-patterns.md
          - 3.7 Barriers and Challenges: modern/3-7-barriers.md
          - 3.8 Recommendations: modern/3-8-recommendations.md
          - 3.9 Lessons: modern/3-9-lessons.md
          - 3.10 Limitations: modern/3-10-limitations.md
      - 4. Modernization Tools:
          - 4.1 Tool Types: modern/4-1-tooltypes.md
          - 4.2 Tool Matrix: modern/4-2-toolmatrix.md
      - 5. Lifecycle Processes:
          - 5.0 Overview: modern/5-0-overview.md
          - 5.1 Agreement Processes: modern/5-1-best.md
          - 5.2 Organizational Project-enabling Processes: modern/5-2-organizational.md
          - 5.3 Technical Management processes: modern/5-3-techmanage.md
          - 5.4 Technical Processes: modern/5-4-tech.md
          - 5.5 Process Application: modern/5-5-application.md
          - 5.6 Application of Life Cycle Processes to Agile Evolutionary and Iterative Life Cycle Models: modern/5-6-agile.md
      - 6. Organization and Support:
          - 6.0 Overview: modern/6-0-overview.md
          - 6.1 Project Team: modern/6-1-project.md
          - 6.2 Technical Team: modern/6-2-tech.md
          - 6.3 Support: modern/6-3-support.md
          - 6.4 Stakeholders: modern/6-4-stakeholders.md
      - 7. Determining the Best Modernization Solution:
          - 7.1 Identifying Viable Solutions: modern/7-1-solutions.md
          - 7.2 Analysis of Alternatives (AoA) Guidance: modern/7-2-alternatives.md
      - 8. Solution Design:
          - 8.1 Requirements: modern/8-1-requirements.md
          - 8.2 Technical Design: modern/8-2-tech.md
          - 8.3 Cybersecurity: modern/8-3-cybersecurity.md
      - 9. Project Guidance:
          - 9.1 Phases: modern/9-1-phases.md
          - 9.2 Risk Identification and Management: modern/9-2-risk.md
      - 10. Measurement and Metrics:
          - 10.1 Define KPIs: modern/10-1-definekpi.md
      - 11. Appendix:
          - '11.1 Appendix A: Sample Design 1': modern/11-appendix-a.md
          - '11.2 Appendix B: Sample Design 2': modern/11-appendix-b.md
          - '11.3 Appendix C: Checklists and Templates': modern/11-appendix-c.md

extra:
  # Update the baseurl for the location of deployment.
  # This value is combined with the playbook urls to build the inter-playbook nav
  # baseurl: https://isobar-us.github.io/USAF-2212-A4UX-Playbook
  baseurl: https://ArrayBESPlaybooks.github.io/ArrayBESPlaybook
  #  baseurl: http://localhost:8000

  # This list
  playbooks:
    - name: Agile
      url: /agile/1-1-purpose
      icon: _assets/0_home_page_icon_agile.svg
      desc: Faster, more dynamic response to customers’ development needs requires a modern management approach. Learn what is necessary to establish those responsive process and management guidelines within the DoD environment.
    - name: Automated Testing
      url: /testing/1-1-purpose
      icon: _assets/0_home_page_icon_automatedtesting.svg
      desc: With the move towards more flexible approaches to software development comes the desire to implement faster, more reliable testing procedures. Learn practical, experienced-based methods and best practices for automating testing.
    - name: User Experience
      url: /ux/1-1-purpose
      icon: _assets/0_home_page_icon_user_experience.svg
      desc: Delivering value requires delivering an experience that meets the needs of your users. Learn what UX is, how it benefits and enhances development efforts, methods for designing experiences, and best-practice visual design guidelines.
    - name: Automated Application Modernization
      url: /modern/1-1-play-1
      icon: _assets/0_home_page_icon_automated_App_modern.svg
    - name: Low-Code
      url: /low-code/1-1-plays
      icon: _assets/0_home_page_icon_agile_Model-Driven.svg
    # - name: DevSec Ops
    #   url: /devops/1-1-devops
    #   icon: _assets/0_home_page_icon_devsec.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus.
    # - name: Cyber Security
    #   url: /cyber/1-1-cyber
    #   icon: _assets/0_home_page_icon_security.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium.
    # - name: App Technology Refresh for Cloud
    #   url: /cloud/1-1-cloud
    #   icon: _assets/0_home_page_icon_cloud.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus, id ornare lectus. purus non justo.
    # - name: Agile Acquistions
    #   url: /acquistions/1-1-acquistions
    #   icon: _assets/0_home_page_icon_agile_acquistions.svg
    #   desc: Proin eu erat felis. Integer cursus consequat metus at dictum. Mauris rhoncus placerat sem. Maecenas bibendum laoreet bibendum. Proin maximus facilisis magna eu egestas. Curabitur feugiat, leo non rhoncus pretium, dolor ex scelerisque purus, id ornare lectus.

  footer:
    AFLCMC/BES:
      Air Force Life Cycle Management Center (AFLCMC): https://www.wpafb.af.mil/aflcmc
      Air Force Business and Enterprise Systems (BES): https://www.airforcebes.af.mil

  section_headers:
    - ../../_assets/_headers/Header01.jpg
    - ../../_assets/_headers/Header02.jpg
    - ../../_assets/_headers/Header03.jpg
    - ../../_assets/_headers/Header04.jpg
    - ../../_assets/_headers/Header05.jpg
    - ../../_assets/_headers/Header06.jpg
    - ../../_assets/_headers/Header07.jpg
    - ../../_assets/_headers/Header08.jpg
    - ../../_assets/_headers/Header09.jpg
  home_headers:
    - _assets/0_home_page_header_01@2x.jpg
    - _assets/0_home_page_header_02@2x.jpg
    - _assets/0_home_page_header_03@2x.jpg
    - _assets/0_home_page_header_04@2x.jpg
